// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyADt1-GRM6XFT---eKQpzGlI3BObenfm_s',
    appId: '1:113166187925:web:fd1eedc54790e01ed44a9c',
    messagingSenderId: '113166187925',
    projectId: 'chat-app-780e7',
    authDomain: 'chat-app-780e7.firebaseapp.com',
    storageBucket: 'chat-app-780e7.firebasestorage.app',
    measurementId: 'G-3TPNZPJFCV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAj7BNaW7g68q51iQyLRIPyXhxLtfrE3h8',
    appId: '1:113166187925:android:d4f9dd9a904d5601d44a9c',
    messagingSenderId: '113166187925',
    projectId: 'chat-app-780e7',
    storageBucket: 'chat-app-780e7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBCLQ_Bu8_q6HM7yAxYP-3xNtWn7SO-U2s',
    appId: '1:113166187925:ios:384c53ce0ce7733bd44a9c',
    messagingSenderId: '113166187925',
    projectId: 'chat-app-780e7',
    storageBucket: 'chat-app-780e7.firebasestorage.app',
    iosClientId: '113166187925-lc1jravb4k4c26bsm3nobfi142rmj2do.apps.googleusercontent.com',
    iosBundleId: 'com.chat.app.chatapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBCLQ_Bu8_q6HM7yAxYP-3xNtWn7SO-U2s',
    appId: '1:113166187925:ios:384c53ce0ce7733bd44a9c',
    messagingSenderId: '113166187925',
    projectId: 'chat-app-780e7',
    storageBucket: 'chat-app-780e7.firebasestorage.app',
    iosClientId: '113166187925-lc1jravb4k4c26bsm3nobfi142rmj2do.apps.googleusercontent.com',
    iosBundleId: 'com.chat.app.chatapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyADt1-GRM6XFT---eKQpzGlI3BObenfm_s',
    appId: '1:113166187925:web:15c2a46af2853685d44a9c',
    messagingSenderId: '113166187925',
    projectId: 'chat-app-780e7',
    authDomain: 'chat-app-780e7.firebaseapp.com',
    storageBucket: 'chat-app-780e7.firebasestorage.app',
    measurementId: 'G-Z5HNBLN5NB',
  );
}
